admin-channels: # Channels for Admin commands
  - 631861137687707656
  - 706545364735623224
command-channels: # Channels for regular commands
  - 785910683517845564
  - 785910789453905980
  - 319472408576655360
  - 540690954429136896
  - 785904425364750368
  - 785904369815388170
  - 785904158002905088
  - 785904274830786581
  - 283922116577853441
  - 540691009898676234
  - 785906782232248371
  - 802696758647980043
  - 573994751620022297
  - 597878565987418115
  - 598530345087926323
  - 573954983188234252
  - 584125067932336151
  - 631861137687707656
  - 706545364735623224

command-prefix: "!"
enable-website-linking: true # Allow map results to link to an external website. Setting this to false, removes the website prompt when adding a new map
enable-media-linking: true # Allow map results to link to a media source. Setting this to false, removes the media prompt when adding a new map

matchmaking: # List of possible queues for people to join
  ranked:  # Must be lowercase
    channel: 631861137687707656 # The channel for this queue
    min-queue-time: 1 # The minimum amount of time in minutes a person can spend in queue
    default-queue-time: 30 # The default amount of time in minutes a person queues for when the queue time isn't specified
    max-queue-time: 120 # The maximum amount of time in minutes a person can spend in queue
    maptags: "ranked" # The map pool to use for this type of queue
    players: 2 # Number of players per match
    teams: 2 # Number of teams per match
    uses-matchmaking: true
    matchmaking-band: 10000 # Match players only within a certain skill level
    uses-bans: false # Use the bans system
    post-notification: true # Post a notification in the channel when someone queues
    notification-text: "Someone is looking for a **ranked** game!\nDM <@934827534510616576> with `!queue ranked` to enter the queue.\nThis person will leave the queue at <t:queueTime>"

  1v1:
    channel: 631861137687707656
    min-queue-time: 1
    default-queue-time: 30
    max-queue-time: 120
    maptags: "1v1"
    players: 2
    teams: 2
    uses-matchmaking: false
    matchmaking-band: 10000
    uses-bans: false
    post-notification: true
    notification-text: "Someone is looking for a **1v1** game!\nDM <@934827534510616576> with `!queue 1v1` to enter the queue.\nThis person will leave the queue at <t:queueTime>"

  2v2:
    channel: 631861137687707656
    min-queue-time: 1
    default-queue-time: 60
    max-queue-time: 120
    maptags: "2v2"
    players: 4
    teams: 2
    uses-matchmaking: false
    matchmaking-band: 10000
    uses-bans: false
    post-notification: true
    notification-text: "Someone is looking for a **2v2** game!\nDM <@934827534510616576> with `!queue 2v2` to enter the queue.\nThis person will leave the queue at <t:queueTime>"

  ffa:
    channel: 631861137687707656
    min-queue-time: 1
    default-queue-time: 60
    max-queue-time: 120
    maptags: "ffa"
    players: 4
    teams: 4
    uses-matchmaking: false
    matchmaking-band: 10000
    uses-bans: false
    post-notification: true
    notification-text: "Someone is looking for a **Free for All** game!\nDM <@934827534510616576> with `!queue ffa` to enter the queue.\nThis person will leave the queue at <t:queueTime>"

  asyncranked:
    channel: 631861137687707656
    min-queue-time: 1
    default-queue-time: 60
    max-queue-time: 120
    maptags: "asyncRanked"
    players: 2
    teams: 2
    uses-matchmaking: true
    matchmaking-band: 10000
    uses-bans: false
    post-notification: true
    notification-text: "Someone is looking for an **async** game!\nDM <@934827534510616576> with `!queue asyncranked` to enter the queue.\nThis person will leave the queue at <t:queueTime>"

mmr-start-value: 0.0 # The mmr value a new player starts at
mmr-minimum: 0.0 # Players cannot go below this MMR
mmr-minimum-enabled: true # Enable minimum MMR
mmr-scales: # Tune how much players earn depending on their ranking. Remove this for a pure ELO experience
  - bronze:
      start: 0 # Win more points if you're above 0 but below 50
      winner: 0.2
      loser: 0.0
      emoji: ""
  - silver:
      start: 50 # Win the proper amount of points if you're above 50 but below 600
      winner: 0.0
      loser: 0.0
      emoji: ":shield:"
  - gold:
      start: 600 # Win less points if you're above 600
      winner: -0.2
      loser: 0.0
      emoji: ":crown:"  # Display emoji for the leaderboard

mmr-decay-amount: 20 # The amount of points to decay by
mmr-decay-every: 2week # The period of time before decay counter resets (1week, 2week, 3week, 1month, 4day, never, etc.)
mmr-decay-start: 150 # The MMR value that decay starts at
mmr-decay-games: 4 # The amount of games to play to avoid decay within the time period
mmr-points-bet: 32 # The maximum amount of mmr of both players combined on the line in a 2 player game
mmr-power: 10 # The to the power of variable in the elo formula
mmr-elo-divide: 400 # The amount to dive the elo by before raising it to the power

game-limit-count: 10 # Number of games you must play every season before you appear on the leaderboard


season-every: 4 # The period of time before we increment the season number in months (1, 2, etc.)
season-normalize: false # Normalize the seasons to be within a certain mmr range
season-normalize-min: 10 # Minimum normalize range
season-normalize-max: 150 # Maximum normalize range

leaderboard-text: "Groove of War players, ranked by Elo rating. Go to <#785910789453905980> and type !ranked to get started with ranked games"  # The text which appears in the body of the leaderboard embed
season-high-leaderboard-text: "Groove of War players, sorted by Season High Elo. Go to <#785910789453905980> and type !ranked to get started with ranked games"  # The text which appears in the body of the leaderboard embed

help-text: "Fitebot uses a custom MMR ranking system, adjusting your rank relative to your opponent's after a match\n

            It supports both ranked and unranked modes. Fitebot can also serve as a map database\n

            !register: Register for ranked matches\n

            !ranked: Shows ranked rules.\n

            !stats: View your stats including your mmr\n

            !gamelimit: View how many games you must play until you appear on the leaderboard\n

            !leaderboard <page>: Displays the current leaderboard as a chat message\n

            !seasonhighs <page>: Displays everyone's season high mmr as a leaderboard chat message\n

            !mapTags <page>: Display all the available map tags to search for in the maps query\n

            !mapTag <tag>: Display all the available maps with a given tag. Can use !mapTag <tag> random\n

            !mapName <name>: Display all the available maps with a given name\n

            !maps <query>: Displays the map pool for the specified query (map names containing the query, or tags matching the query). Can use !maps <query> random\n

            !queue <queue> 15: See !match\n

            !match <queue> 15: DM this to the bot to enter a matchmaker queue which expires after 15 minutes\n

            !cancel <queue>: DM this to the bot to leave the matchmaking queue\n

            !iwin: Type !iwin @opponent#1234 if you won against your opponent. This command is for manually entering in match data\n

            !ilose: Type !ilose @opponent#1234 if you lost against your opponent. This command is for manually entering in match data\n
            
            !season <number>: Type !season to view the current season number and when the next season starts. Type !season <season number> to see the leaderboard for that season.\n

            When registered, we store your discord ID, tag and map creations in a database. Please contact an admin if you would like them to be removed"

ranked-text: "Our <#806343595690033172> uses a custom MMR ranking system, adjusting your rank relative to your opponent's after a match\n
            CO Bans: Ryota, Caesar, Ragna and Koji. Players may optionally ban their opponent from playing 3 additional COs\n\n
            1. Please be respectful to your opponent, if it's early in the game and they have to leave, don't report the match results\n
            2. It's up to the winner to report the results, the loser may do so if they wish. If no results are reported the match is unranked\n
            3. Only one of the players must report their win/loss. Please contact an admin for MMR correction if both players to do so\n
            4. The `ranked` queue is only for live games with a 60min chess timer\n
            5. The `asyncranked` queue is for async games with no timer, but can be played live\n
            6. Players will only play ranked games on maps from the `!maps ranked` pool for live matches\n
            7. Players will only play async ranked games on maps from the `!maps rankedasync` pool for async matches\n
            8. The players may agree on a map other than the suggested map, however if they cannot agree on a map, the suggested map is played\n
            \n
            These are the guidelines for ranked. Please contact an admin for any clarifications"

discord-bot-token: # Discord bot token

mysql-hostname: # Mysql server hostname
mysql-database: # Mysql db name
mysql-user: # Mysql username
mysql-password: # Mysql password